name: Issues event
on: issues

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GH context
        run: |
          echo "The title created was ${{ github.event.issue.title }}"
          echo "The body was ${{ github.event.issue.body }}"
